version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

