name: Build & Test

on:
  push:
  schedule:
  - cron:  '0 3 * * 1'


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update -n base -f environment.yml
        pip install . --no-deps
    - name: Test with pytest
      run: |
        conda install pytest
        pytest test

  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat install -c bioconda 'hmmer>=3.1'
        C:\Miniconda\condabin\conda.bat init powershell
        pip install . --no-deps
    - name: Test with pytest
      run: |
        C:\Miniconda\condabin\conda.bat activate base
        C:\Miniconda\condabin\conda.bat install pytest
        pytest test
